services:
  postgres:
    container_name: "postgres"
    image: "postgres:latest"
    restart: always
    tty: true
    stdin_open: true
    logging:
      driver: "json-file"
      options:
        max-size: "1g"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGPORT: 5432
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data